### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by LocoPineapples** [jaacksondev/etched#10]
[crash-2021-07-10_22.26.45-client.txt](https://github.com/jaacksondev/etched/files/6796252/crash-2021-07-10_22.26.45-client.txt)

So, I had etched working fine for a while. After I removed two mods, ExtraOrigins and TooManyOrigins, it started giving me this crash log if I try to start up without them. If I add them back into the mods folder it'll work fine, even if they're disabled. Without them, though, Etched just won't let the game launch.

**Comment by jaacksondev** [comment]
Not an issue with etched, it seems to be caused by Unique Origins refencing a class which doesn't exist.
