### ISSUE TITLE
file type "audio/mp3" works on radios, but not on discs

### ISSUE THREAD

**Issue by Brappan** [jaacksondev/etched#117]
The file type audio/mp3 works on the radio block but not on the etching table.

https://github.com/user-attachments/assets/89427624-2998-4d17-97cd-165fd7489fa4

music link used in video:
https://audio.jukehost.co.uk/P6nAiMl9h3VyxvzkwhxiRWh7rxUxVHyi

**Comment by Brappan** [comment]
made this account just to report this so if you need me to reply i might not answer for a while

**Comment by fyrkantis** [comment]
I'm also having this exact issue, with music hosted on the web as audio/mp3.

Using Forge 47.3.0 (Minecraft 1.20.1) with Etched 3.0.2, along with some other mods.
