### ISSUE TITLE
Crash with Fabric & Quilt

### ISSUE THREAD

**Issue by rsp4jack** [jaacksondev/etched#54]
### What version are you seeing the problem on?

1.18.2

### Describe the issue

```markdown
Start it
```

### latest.log

```shell
https://0bin.net/paste/Ce6olwmi#FsGwFbQEg95XwME2Fn4uZQ9mgZ3uvpTGBtIdDt9gNhR
```

**Comment by rsp4jack** [comment]
Also crashes on Fabric 1.18.2

**Comment by Ocelot5836** [comment]
The provided log doesn't lead anywhere. I need the log to fix the issue.
