### ISSUE TITLE
Server crashes when right-clicking

### ISSUE THREAD

**Issue by lbgs** [jaacksondev/etched#61]
### What version are you seeing the problem on?

1.16.5

### Describe the issue

```markdown
Integrate the package Above+And+Beyond 1.3 Server, and install the scheduled forge 2.0.0+1.16.5. After synthesizing Album cover and Boombox, right-click and the server crashes directly
```

### latest.log

```shell
none
```

**Comment by jacksonhardaway** [comment]
Please provide the latest.log from the server

**Comment by lbgs** [comment]
[latest.log](https://github.com/MoonflowerTeam/etched/files/11787627/latest.log)

**Comment by Ocelot5836** [comment]
This seems like an environment issue. The error happens in vanilla mc code.
