### ISSUE TITLE
Music is always tagged as Custom Music

### ISSUE THREAD

**Issue by GitJhopa** [jaacksondev/etched#65]
### What version are you seeing the problem on?

1.19.2

### Describe the issue

For some reason, the names of the tracks are not indicated, Custom Music is everywhere
http://music.arizona-rp.com/rodina/1688162477.mp3

Here is an example link 
or

https://apalice.ru/1.mp3
Everywhere I get Custom Music, it feels like it does not take information about track names from .mp3
![image](https://github.com/MoonflowerTeam/etched/assets/86250668/d9cbba79-c7b9-4706-8611-30979199e5a6)

### latest.log

```shell
no logs
```

**Comment by jacksonhardaway** [comment]
Intended, right click the record label to customize it.

**Comment by M0l1bden** [comment]
Right click doesnt do any anything
