### ISSUE TITLE
Memory leak, hard freezes and FPS lags.

### ISSUE THREAD

**Issue by GitJhopa** [jaacksondev/etched#68]
### What version are you seeing the problem on?

1.19.2

### Describe the issue

1. Place radio or Boombox
2. Specify a link, for example, to favicon.ico on any site, here is an example of the link that the player indicated and the eternal download of the track began and minecraft began to freeze, the fps dropped and the RAM on F3 began to change very quickly

URL freeze game: https://pastebin.com/1a4MLEtM

### latest.log

```shell
https://pastebin.com/ysE62QGG
```

**Comment by GitJhopa** [comment]
https://youtu.be/HuozT-dVmMA Here's an example of what happens to RAM, after a track is loaded, it goes berserk. The video is 60 FPS, so you won't see all the speed, but it feels like it is cleared and used every 0.01ms

**Comment by Ocelot5836** [comment]
Based on the video and some testing I just did it seems the player just doesn't have enough memory allocated for a large modpack. The video is normal java behavior when out of memory to try and keep the game running.

**Comment by GitJhopa** [comment]
> Based on the video and some testing I just did it seems the player just doesn't have enough memory allocated for a large modpack. The video is normal java behavior when out of memory to try and keep the game running.

noo bro see this lol

https://github.com/MoonflowerTeam/etched/assets/86250668/01636daf-9123-4b28-92af-3f1a675ababd

**Comment by GitJhopa** [comment]
There is enough memory allocated, I have few mods. As I point to a link not to .mp3 Your mod tries to load something forever and the RAM goes crazy, the CPU starts to load with it and minecraft starts to lag

**Comment by GitJhopa** [comment]
need fix! it's a mod bug!

**Comment by Ocelot5836** [comment]
The mod only allocates 32kb of ram for audio buffers once which wouldn't cause garbage collection like that. Minecraft wastes ~2mb per frame in the render loop, so as framerate goes up the garbage collector runs more often to try and reclaim that memory. There is only 2gb of ram on the computer, so java can only use ~1.2gb of ram maximum to leave space for other processing. You can try using a different java max memory value (such as `-Xmx 1g`) to prevent java from running the garbage collector as often.

**Comment by GitJhopa** [comment]
No fixed!

**Comment by GitJhopa** [comment]
https://rux.muzmo.cc/info?id=76191746 use this URL in RADIO and see F3 for USES RAM.

**Comment by GitJhopa** [comment]
Is it really difficult for you to test and help solve the problem? Your mod is always trying to load a track that doesn't exist and the RAM just goes crazy with any jvm arguments.

**Comment by GitJhopa** [comment]
13GB - it's not normal!


https://github.com/MoonflowerTeam/etched/assets/86250668/6a9285de-0b70-46a0-944c-8ad555573631

**Comment by fewizz** [comment]
> https://rux.muzmo.cc/info?id=76191746 use this URL in RADIO and see F3 for USES RAM.

this link points to a web page, not a file

**Comment by GitJhopa** [comment]
> > https://rux.muzmo.cc/info?id=76191746 use this URL in RADIO and see F3 for USES RAM.
> 
> this link points to a web page, not a file

yes! it creates lag!

**Comment by GitJhopa** [comment]
Any link not .mp3 - creates game lags and nonsense is going on with RAM! read the topic!

**Comment by GitJhopa** [comment]
need fix.
