### ISSUE TITLE
REOPEN!! Memory leak, hard freezes and FPS lags. #68

### ISSUE THREAD

**Issue by GitJhopa** [jaacksondev/etched#74]
### What version are you seeing the problem on?

1.19.2

### Describe the issue

1. Place radio or Boombox
2. Specify a link, for example, to favicon.ico on any site, here is an example of the link that the player indicated and the eternal download of the track began and minecraft began to freeze, the fps dropped and the RAM on F3 began to change very quickly

https://youtu.be/HuozT-dVmMA Here's an example of what happens to RAM, after a track is loaded, it goes berserk. The video is 60 FPS, so you won't see all the speed, but it feels like it is cleared and used every 0.01ms

There is enough memory allocated, I have few mods. As I point to a link not to .mp3 Your mod tries to load something forever and the RAM goes crazy, the CPU starts to load with it and minecraft starts to lag

Any link not .mp3 - creates game lags and nonsense is going on with RAM! read the topic!

### latest.log

```shell
https://pastebin.com/ysE62QGG
```

**Comment by GitJhopa** [comment]
The solution to the problem is very simple. Prevent link processing if there is no .mp3 at the end of the link

**Comment by GitJhopa** [comment]
One player can break minecraft for all players, he just puts a radio on spawn and enters any link there that does not lead to an .mp3 track - and a memory leak starts, severe client freezes, fps goes up to 5-10 frames.

**Comment by GitJhopa** [comment]
https://spark.lucko.me/6PvmUixfMn client spark

**Comment by GitJhopa** [comment]
thank you

**Comment by Ocelot5836** [comment]
Next time don't open multiple issues and say what the problem is. The first issue just said it was a problem with etched without any context.

**Comment by GitJhopa** [comment]
ok
