### ISSUE TITLE
1.16.5 Crash

### ISSUE THREAD

**Issue by ElLiox** [jaacksondev/etched#81]
When inserting a disc into a jukebox through a hopper, the game simply crashes

etched-forge-2.2.0+1.16.5
pollen-forge-1.5.0+1.16.5

[crash-2024-01-30_17.45.00-server.txt](https://github.com/jacksonhardaway/etched/files/14104020/crash-2024-01-30_17.45.00-server.txt)

**Comment by Ocelot5836** [comment]
Issue with `deadguysuntitleddeepdark`
