### ISSUE TITLE
Has Fabric support been dropped?

### ISSUE THREAD

**Issue by brawaru** [jaacksondev/etched#82]
Hey, noticed there isn't a Fabric version for 1.20.x, and all the code for it seems to be removed. At first thought you migrated to architectury, but you seem to depend on Forge if I read it correctly. Has Fabric support been dropped for good? If so, what were the reasons? Not trying to judge or anything, just genuinely curious. Love the mod btw, thanks for developing it.

**Comment by Ocelot5836** [comment]
Fabric support was dropped because we're going to move exclusively to NeoForge 1.21. The api so far is massively better than Forge, Fabric, and Architectury. It's always possible to port to architectury at some point in the future, but it takes more effort to maintain than a mod on a single platform.

**Comment by snarkyalyx** [comment]
Just for discoverability (since this result is the first on Google), someone is working on an Etched 1.20.x for Quilt/Fabric in this fork here https://github.com/VanderCat/etched-quilt

**Comment by kingniu4** [comment]
this fabric fork version:

1. villager can't have job.
2. boombox image error
3. hope new version

**Comment by yoblex** [comment]
> Fabric support was dropped because we're going to move exclusively to NeoForge 1.21. The api so far is massively better than Forge, Fabric, and Architectury. It's always possible to port to architectury at some point in the future, but it takes more effort to maintain than a mod on a single platform.

NeoForge is the worst server core, for example on a server with 50 online I have 3-5 TPS, and on Forge + async Performant around 19-20, why was it necessary to switch completely to NeoForge if it is an unoptimized piece of crap?
