### ISSUE TITLE
Etched Music Discs won't stop "playing" after track ends (Etched 3.0.1)

### ISSUE THREAD

**Issue by justalittlemango** [jaacksondev/etched#84]
### What version are you seeing the problem on?
1.20.1 

### Describe the issue
1. Install Etched 3.0.1 only, run on Minecraft 1.20.1, Forge Version 47.2.1
2. Play any track from a vanilla jukebox
3. Place a hopper directly underneath the jukebox

The problem with this is that as an Etched Music Disc ends, it keeps on "playing" which makes the hopper locked, retaining Redstone power, which could cause some issues in vanilla music disc Redstone contraptions. I do think that this is an unintentional feature though. Not exactly sure where the problem is. 

Anyways, this mod is really great! hoping for this to get resolved though

### latest.log
_(not needed)_

Video: 
https://github.com/jacksonhardaway/etched/assets/159528715/087a8f3c-4951-4ab6-9934-738d786355dc

**Comment by Ocelot5836** [comment]
There really isn't a solution to this because the server doesn't know how long the playing song is. It also doesn't make sense to add a bunch of extra overhead to the server to figure that out just for one feature.
