### ISSUE TITLE
[1.20.1] Game Crashing During Load

### ISSUE THREAD

**Issue by HockeyZman2000** [jaacksondev/etched#85]
Trying to make a custom modpack. Without Etched installed it loads correctly to the main menu. With the mod installed it crashes at the "Mod gather: dispatching CONSTRUCT" stage with the following crash report and log.

Crash Report: 
[crash-2024-02-09_21.49.33-client.txt](https://github.com/jacksonhardaway/etched/files/14227815/crash-2024-02-09_21.49.33-client.txt)

Latest Log: 
[latest.log](https://github.com/jacksonhardaway/etched/files/14227816/latest.log

I'm using Etched 3.0.1 and Forge 47.2.20

**Comment by Ocelot5836** [comment]
This appears to be an issue with oculus. I checked the mixins and oculus is erroring with a different mod.
