### ISSUE TITLE
Drobox links still do not work in newest update

### ISSUE THREAD

**Issue by PosingCarton** [jaacksondev/etched#86]
When I copy the link and paste it into the text box, it says "Unsupported Content-Type: text/html;charset=utf-8"
Here is the link I am using 
https://www.dropbox.com/s/7sd69p3k7cfjy57/A%20Boss%20Approaches%20-%20Super%20Mario%203D%20World%20%28128%20kbps%29.ogg?dl=0

**Comment by justalittlemango** [comment]
Change the dl=0 into dl=1 in the URL to allow direct downloads, tried it and it works 100%
