### ISSUE TITLE
Complex Music Labels don't keep data.

### ISSUE THREAD

**Issue by awesomeguy2000** [jaacksondev/etched#88]
If you edit a complex music label by right-clicking, the saved data is reset when moving the complex music label in the inventory.

**Comment by Ocelot5836** [comment]
Can't reproduce in 1.20.1

**Comment by Aspurgus** [comment]
> If you edit a complex music label by right-clicking, the saved data is reset when moving the complex music label in the inventory.

What other mods do you have installed? Im getting the same issue in my modpack but it doesnt happen if only etched is installed

**Comment by Aspurgus** [comment]
a really strange issue, if you name the label before you turn it into a complex label it saves the data, but if you name the complex label after crafting it it will not keep data when moved. However, on the same minecraft instance in a new world, the labels save data perfectly fine. No clue what causes it
